/home/lab/llvm-project/build/bin/llvm-ar rcs lib/libArduCopter_libs.a \

llvm-link \
 libraries/AP_AccelCal/AP_AccelCal.cpp.0.o \
 libraries/AP_AccelCal/AccelCalibrator.cpp.0.o \
 libraries/AP_ADC/AP_ADC_ADS1115.cpp.0.o \
 libraries/AP_AHRS/AP_AHRS_DCM.cpp.0.o \
 libraries/AP_AHRS/AP_AHRS_NavEKF.cpp.0.o \
 libraries/AP_AHRS/AP_AHRS_View.cpp.0.o \
 libraries/AP_AHRS/AP_AHRS.cpp.4.o \
 libraries/AP_Airspeed/AP_Airspeed_Backend.cpp.0.o \
 libraries/AP_Airspeed/AP_Airspeed_DLVR.cpp.0.o \
 libraries/AP_Airspeed/AP_Airspeed_Health.cpp.0.o \
 libraries/AP_Airspeed/AP_Airspeed_MS4525.cpp.0.o \
 libraries/AP_Airspeed/AP_Airspeed_MS5525.cpp.0.o \
 libraries/AP_Airspeed/AP_Airspeed_SDP3X.cpp.0.o \
 libraries/AP_Airspeed/AP_Airspeed_UAVCAN.cpp.0.o \
 libraries/AP_Airspeed/AP_Airspeed_analog.cpp.0.o \
 libraries/AP_Airspeed/Airspeed_Calibration.cpp.0.o \
 libraries/AP_Airspeed/AP_Airspeed.cpp.4.o \
 libraries/AP_Baro/AP_Baro_BMP085.cpp.0.o \
 libraries/AP_Baro/AP_Baro_BMP280.cpp.0.o \
 libraries/AP_Baro/AP_Baro_BMP388.cpp.0.o \
 libraries/AP_Baro/AP_Baro_Backend.cpp.0.o \
 libraries/AP_Baro/AP_Baro_DPS280.cpp.0.o \
 libraries/AP_Baro/AP_Baro_FBM320.cpp.0.o \
 libraries/AP_Baro/AP_Baro_HIL.cpp.0.o \
 libraries/AP_Baro/AP_Baro_ICM20789.cpp.0.o \
 libraries/AP_Baro/AP_Baro_KellerLD.cpp.0.o \
 libraries/AP_Baro/AP_Baro_LPS2XH.cpp.0.o \
 libraries/AP_Baro/AP_Baro_MS5611.cpp.0.o \
 libraries/AP_Baro/AP_Baro_SPL06.cpp.0.o \
 libraries/AP_Baro/AP_Baro_UAVCAN.cpp.0.o \
 libraries/AP_Baro/AP_Baro.cpp.4.o \
 libraries/AP_Baro/AP_Baro_SITL.cpp.4.o \
 libraries/AP_BattMonitor/AP_BattMonitor_Analog.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_BLHeliESC.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_Bebop.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_FuelFlow.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_PWM.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Maxell.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_SMBus_NeoDesign.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_SMBus_SUI.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Solo.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp.0.o \
 libraries/AP_BattMonitor/AP_BattMonitor.cpp.4.o \
 libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp.4.o \
 libraries/AP_BoardConfig/IMU_heater.cpp.0.o \
 libraries/AP_BoardConfig/board_drivers.cpp.0.o \
 libraries/AP_BoardConfig/canbus_interface.cpp.0.o \
 libraries/AP_BoardConfig/canbus_slcan.cpp.0.o \
 libraries/AP_BoardConfig/AP_BoardConfig.cpp.4.o \
 libraries/AP_BoardConfig/AP_BoardConfig_CAN.cpp.4.o \
 libraries/AP_BoardConfig/canbus_driver.cpp.4.o \
 libraries/AP_Common/AP_Common.cpp.0.o \
 libraries/AP_Common/AP_ExpandingArray.cpp.0.o \
 libraries/AP_Common/AP_FWVersion.cpp.0.o \
 libraries/AP_Common/Location.cpp.0.o \
 libraries/AP_Common/c++.cpp.0.o \
 libraries/AP_Compass/AP_Compass_AK09916.cpp.0.o \
 libraries/AP_Compass/AP_Compass_AK8963.cpp.0.o \
 libraries/AP_Compass/AP_Compass_BMM150.cpp.0.o \
 libraries/AP_Compass/AP_Compass_Calibration.cpp.0.o \
 libraries/AP_Compass/AP_Compass_HIL.cpp.0.o \
 libraries/AP_Compass/AP_Compass_HMC5843.cpp.0.o \
 libraries/AP_Compass/AP_Compass_IST8308.cpp.0.o \
 libraries/AP_Compass/AP_Compass_IST8310.cpp.0.o \
 libraries/AP_Compass/AP_Compass_LIS3MDL.cpp.0.o \
 libraries/AP_Compass/AP_Compass_LSM303D.cpp.0.o \
 libraries/AP_Compass/AP_Compass_LSM9DS1.cpp.0.o \
 libraries/AP_Compass/AP_Compass_MAG3110.cpp.0.o \
 libraries/AP_Compass/AP_Compass_MMC3416.cpp.0.o \
 libraries/AP_Compass/AP_Compass_QMC5883L.cpp.0.o \
 libraries/AP_Compass/AP_Compass_RM3100.cpp.0.o \
 libraries/AP_Compass/AP_Compass_SITL.cpp.0.o \
 libraries/AP_Compass/AP_Compass_UAVCAN.cpp.0.o \
 libraries/AP_Compass/CompassCalibrator.cpp.0.o \
 libraries/AP_Compass/Compass_PerMotor.cpp.0.o \
 libraries/AP_Compass/Compass_learn.cpp.0.o \
 libraries/AP_Compass/AP_Compass.cpp.4.o \
 libraries/AP_Compass/AP_Compass_Backend.cpp.4.o \
 libraries/AP_Declination/AP_Declination.cpp.0.o \
 libraries/AP_Declination/tables.cpp.0.o \
 libraries/AP_GPS/AP_GPS.cpp.0.o \
 libraries/AP_GPS/AP_GPS_ERB.cpp.0.o \
 libraries/AP_GPS/AP_GPS_GSOF.cpp.0.o \
 libraries/AP_GPS/AP_GPS_MAV.cpp.0.o \
 libraries/AP_GPS/AP_GPS_MTK.cpp.0.o \
 libraries/AP_GPS/AP_GPS_MTK19.cpp.0.o \
 libraries/AP_GPS/AP_GPS_NMEA.cpp.0.o \
 libraries/AP_GPS/AP_GPS_NOVA.cpp.0.o \
 libraries/AP_GPS/AP_GPS_SBF.cpp.0.o \
 libraries/AP_GPS/AP_GPS_SBP.cpp.0.o \
 libraries/AP_GPS/AP_GPS_SBP2.cpp.0.o \
 libraries/AP_GPS/AP_GPS_SIRF.cpp.0.o \
 libraries/AP_GPS/AP_GPS_UAVCAN.cpp.0.o \
 libraries/AP_GPS/AP_GPS_UBLOX.cpp.0.o \
 libraries/AP_GPS/GPS_Backend.cpp.0.o \
 libraries/AP_GPS/RTCM3_Parser.cpp.0.o \
 libraries/AP_HAL/Device.cpp.0.o \
 libraries/AP_HAL/HAL.cpp.0.o \
 libraries/AP_HAL/RCOutput.cpp.0.o \
 libraries/AP_HAL/Scheduler.cpp.0.o \
 libraries/AP_HAL/Semaphores.cpp.0.o \
 libraries/AP_HAL/Storage.cpp.0.o \
 libraries/AP_HAL/Util.cpp.0.o \
 libraries/AP_HAL/system.cpp.0.o \
 libraries/AP_HAL/utility/BetterStream.cpp.0.o \
 libraries/AP_HAL/utility/RCOutput_Tap.cpp.0.o \
 libraries/AP_HAL/utility/RCOutput_Tap_Linux.cpp.0.o \
 libraries/AP_HAL/utility/RingBuffer.cpp.0.o \
 libraries/AP_HAL/utility/Socket.cpp.0.o \
 libraries/AP_HAL/utility/dsm.cpp.0.o \
 libraries/AP_HAL/utility/ftoa_engine.cpp.0.o \
 libraries/AP_HAL/utility/getopt_cpp.cpp.0.o \
 libraries/AP_HAL/utility/packetise.cpp.0.o \
 libraries/AP_HAL/utility/print_vprintf.cpp.0.o \
 libraries/AP_HAL/utility/replace.cpp.0.o \
 libraries/AP_HAL/utility/srxl.cpp.0.o \
 libraries/AP_HAL/utility/st24.cpp.0.o \
 libraries/AP_HAL/utility/sumd.cpp.0.o \
 libraries/AP_HAL/utility/utoa_invert.cpp.0.o \
 libraries/AP_HAL_Empty/AnalogIn.cpp.0.o \
 libraries/AP_HAL_Empty/GPIO.cpp.0.o \
 libraries/AP_HAL_Empty/HAL_Empty_Class.cpp.0.o \
 libraries/AP_HAL_Empty/RCInput.cpp.0.o \
 libraries/AP_HAL_Empty/RCOutput.cpp.0.o \
 libraries/AP_HAL_Empty/Scheduler.cpp.0.o \
 libraries/AP_HAL_Empty/Semaphores.cpp.0.o \
 libraries/AP_HAL_Empty/Storage.cpp.0.o \
 libraries/AP_HAL_Empty/UARTDriver.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_ADIS1647x.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_BMI055.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_BMI160.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_HIL.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_Invensensev2.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_L3G4200D.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS0.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS1.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_RST.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp.0.o \
 libraries/AP_InertialSensor/AuxiliaryBus.cpp.0.o \
 libraries/AP_InertialSensor/BatchSampler.cpp.0.o \
 libraries/AP_InertialSensor/AP_InertialSensor.cpp.4.o \
 libraries/AP_Math/AP_GeodesicGrid.cpp.0.o \
 libraries/AP_Math/AP_Math.cpp.0.o \
 libraries/AP_Math/crc.cpp.0.o \
 libraries/AP_Math/location.cpp.0.o \
 libraries/AP_Math/location_double.cpp.0.o \
 libraries/AP_Math/matrix3.cpp.0.o \
 libraries/AP_Math/matrixN.cpp.0.o \
 libraries/AP_Math/matrix_alg.cpp.0.o \
 libraries/AP_Math/polygon.cpp.0.o \
 libraries/AP_Math/quaternion.cpp.0.o \
 libraries/AP_Math/spline5.cpp.0.o \
 libraries/AP_Math/vector2.cpp.0.o \
 libraries/AP_Math/vector3.cpp.0.o \
 libraries/AP_Mission/AP_Mission_Commands.cpp.0.o \
 libraries/AP_Mission/AP_Mission.cpp.4.o \
 libraries/AP_NavEKF/AP_NavEKF_core_common.cpp.0.o \
 libraries/AP_NavEKF/AP_Nav_Common.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_AirDataFusion.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_Control.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_Logging.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_MagFusion.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_Measurements.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_OptFlowFusion.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_Outputs.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_PosVelFusion.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_RngBcnFusion.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_VehicleStatus.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2_core.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF_GyroBias.cpp.0.o \
 libraries/AP_NavEKF2/AP_NavEKF2.cpp.4.o \
 libraries/AP_NavEKF3/AP_NavEKF3_AirDataFusion.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_GyroBias.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_OptFlowFusion.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_RngBcnFusion.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_VehicleStatus.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3_core.cpp.0.o \
 libraries/AP_NavEKF3/AP_NavEKF3.cpp.4.o \
 libraries/AP_Notify/AP_BoardLED.cpp.0.o \
 libraries/AP_Notify/AP_BoardLED2.cpp.0.o \
 libraries/AP_Notify/AP_Notify.cpp.0.o \
 libraries/AP_Notify/Buzzer.cpp.0.o \
 libraries/AP_Notify/DiscoLED.cpp.0.o \
 libraries/AP_Notify/DiscreteRGBLed.cpp.0.o \
 libraries/AP_Notify/Display.cpp.0.o \
 libraries/AP_Notify/Display_SH1106_I2C.cpp.0.o \
 libraries/AP_Notify/Display_SITL.cpp.0.o \
 libraries/AP_Notify/Display_SSD1306_I2C.cpp.0.o \
 libraries/AP_Notify/ExternalLED.cpp.0.o \
 libraries/AP_Notify/Led_Sysfs.cpp.0.o \
 libraries/AP_Notify/MMLPlayer.cpp.0.o \
 libraries/AP_Notify/NCP5623.cpp.0.o \
 libraries/AP_Notify/NeoPixel.cpp.0.o \
 libraries/AP_Notify/OreoLED_I2C.cpp.0.o \
 libraries/AP_Notify/PCA9685LED_I2C.cpp.0.o \
 libraries/AP_Notify/PixRacerLED.cpp.0.o \
 libraries/AP_Notify/ProfiLED.cpp.0.o \
 libraries/AP_Notify/RCOutputRGBLed.cpp.0.o \
 libraries/AP_Notify/RGBLed.cpp.0.o \
 libraries/AP_Notify/SITL_SFML_LED.cpp.0.o \
 libraries/AP_Notify/SerialLED.cpp.0.o \
 libraries/AP_Notify/ToneAlarm.cpp.0.o \
 libraries/AP_Notify/ToshibaLED_I2C.cpp.0.o \
 libraries/AP_Notify/UAVCAN_RGB_LED.cpp.0.o \
 libraries/AP_Notify/VRBoard_LED.cpp.0.o \
 libraries/AP_OpticalFlow/AP_OpticalFlow_CXOF.cpp.0.o \
 libraries/AP_OpticalFlow/AP_OpticalFlow_HereFlow.cpp.0.o \
 libraries/AP_OpticalFlow/AP_OpticalFlow_MAV.cpp.0.o \
 libraries/AP_OpticalFlow/AP_OpticalFlow_Onboard.cpp.0.o \
 libraries/AP_OpticalFlow/AP_OpticalFlow_PX4Flow.cpp.0.o \
 libraries/AP_OpticalFlow/AP_OpticalFlow_Pixart.cpp.0.o \
 libraries/AP_OpticalFlow/AP_OpticalFlow_SITL.cpp.0.o \
 libraries/AP_OpticalFlow/OpticalFlow.cpp.0.o \
 libraries/AP_OpticalFlow/OpticalFlow_backend.cpp.0.o \
 libraries/AP_Param/AP_Param.cpp.0.o \
 libraries/AP_Rally/AP_Rally.cpp.4.o \
 libraries/AP_RangeFinder/AP_RangeFinder_BBB_PRU.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_BLPing.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_Bebop.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_Benewake.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_Benewake_TFMiniPlus.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_Lanbao.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_LeddarOne.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_LightWareI2C.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_MAVLink.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarI2CXL.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarSerialLV.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_NMEA.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_PWM.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_PulsedLightLRF.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_TeraRangerI2C.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_UAVCAN.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_VL53L0X.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_VL53L1X.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_Wasp.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_analog.cpp.0.o \
 libraries/AP_RangeFinder/AP_RangeFinder_uLanding.cpp.0.o \
 libraries/AP_RangeFinder/RangeFinder_Backend.cpp.0.o \
 libraries/AP_RangeFinder/RangeFinder.cpp.4.o \
 libraries/AP_Scheduler/PerfInfo.cpp.0.o \
 libraries/AP_Scheduler/AP_Scheduler.cpp.4.o \
 libraries/AP_SerialManager/AP_SerialManager.cpp.0.o \
 libraries/AP_Terrain/AP_Terrain.cpp.0.o \
 libraries/AP_Terrain/TerrainGCS.cpp.0.o \
 libraries/AP_Terrain/TerrainIO.cpp.0.o \
 libraries/AP_Terrain/TerrainMission.cpp.0.o \
 libraries/AP_Terrain/TerrainUtil.cpp.0.o \
 libraries/AP_Vehicle/AP_Vehicle.cpp.0.o \
 libraries/AP_InternalError/AP_InternalError.cpp.0.o \
 libraries/AP_Logger/AP_Logger.cpp.0.o \
 libraries/AP_Logger/AP_Logger_Block.cpp.0.o \
 libraries/AP_Logger/AP_Logger_DataFlash.cpp.0.o \
 libraries/AP_Logger/AP_Logger_MAVLink.cpp.0.o \
 libraries/AP_Logger/AP_Logger_MAVLinkLogTransfer.cpp.0.o \
 libraries/AP_Logger/AP_Logger_SITL.cpp.0.o \
 libraries/AP_Logger/LogFile.cpp.0.o \
 libraries/AP_Logger/LoggerMessageWriter.cpp.0.o \
 libraries/AP_Logger/AP_Logger_Backend.cpp.4.o \
 libraries/AP_Logger/AP_Logger_File.cpp.4.o \
 libraries/Filter/DerivativeFilter.cpp.0.o \
 libraries/Filter/HarmonicNotchFilter.cpp.0.o \
 libraries/Filter/LowPassFilter.cpp.0.o \
 libraries/Filter/LowPassFilter2p.cpp.0.o \
 libraries/Filter/NotchFilter.cpp.0.o \
 libraries/GCS_MAVLink/GCS.cpp.0.o \
 libraries/GCS_MAVLink/GCS_DeviceOp.cpp.0.o \
 libraries/GCS_MAVLink/GCS_FTP.cpp.0.o \
 libraries/GCS_MAVLink/GCS_Fence.cpp.0.o \
 libraries/GCS_MAVLink/GCS_MAVLink.cpp.0.o \
 libraries/GCS_MAVLink/GCS_Param.cpp.0.o \
 libraries/GCS_MAVLink/GCS_Rally.cpp.0.o \
 libraries/GCS_MAVLink/GCS_ServoRelay.cpp.0.o \
 libraries/GCS_MAVLink/GCS_Signing.cpp.0.o \
 libraries/GCS_MAVLink/GCS_serial_control.cpp.0.o \
 libraries/GCS_MAVLink/MAVLink_routing.cpp.0.o \
 libraries/GCS_MAVLink/MissionItemProtocol.cpp.0.o \
 libraries/GCS_MAVLink/MissionItemProtocol_Fence.cpp.0.o \
 libraries/GCS_MAVLink/MissionItemProtocol_Rally.cpp.0.o \
 libraries/GCS_MAVLink/MissionItemProtocol_Waypoints.cpp.0.o \
 libraries/GCS_MAVLink/GCS_Common.cpp.4.o \
 libraries/RC_Channel/RC_Channel.cpp.0.o \
 libraries/RC_Channel/RC_Channels.cpp.0.o \
 libraries/SRV_Channel/SRV_Channel.cpp.0.o \
 libraries/SRV_Channel/SRV_Channel_aux.cpp.0.o \
 libraries/SRV_Channel/SRV_Channels.cpp.4.o \
 libraries/StorageManager/StorageManager.cpp.4.o \
 libraries/AP_Tuning/AP_Tuning.cpp.0.o \
 libraries/AP_RPM/AP_RPM.cpp.0.o \
 libraries/AP_RPM/RPM_Backend.cpp.0.o \
 libraries/AP_RPM/RPM_Pin.cpp.0.o \
 libraries/AP_RPM/RPM_SITL.cpp.0.o \
 libraries/AP_RSSI/AP_RSSI.cpp.0.o \
 libraries/AP_Mount/AP_Mount.cpp.0.o \
 libraries/AP_Mount/AP_Mount_Alexmos.cpp.0.o \
 libraries/AP_Mount/AP_Mount_Backend.cpp.0.o \
 libraries/AP_Mount/AP_Mount_SToRM32.cpp.0.o \
 libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp.0.o \
 libraries/AP_Mount/AP_Mount_Servo.cpp.0.o \
 libraries/AP_Mount/AP_Mount_SoloGimbal.cpp.0.o \
 libraries/AP_Mount/SoloGimbal.cpp.0.o \
 libraries/AP_Mount/SoloGimbalEKF.cpp.0.o \
 libraries/AP_Mount/SoloGimbal_Parameters.cpp.0.o \
 libraries/AP_Module/AP_Module.cpp.0.o \
 libraries/AP_Button/AP_Button.cpp.0.o \
 libraries/AP_ICEngine/AP_ICEngine.cpp.0.o \
 libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp.4.o \
 libraries/AP_FlashStorage/AP_FlashStorage.cpp.0.o \
 libraries/AP_Relay/AP_Relay.cpp.0.o \
 libraries/AP_ServoRelayEvents/AP_ServoRelayEvents.cpp.0.o \
 libraries/AP_Volz_Protocol/AP_Volz_Protocol.cpp.0.o \
 libraries/AP_SBusOut/AP_SBusOut.cpp.0.o \
 libraries/AP_IOMCU/AP_IOMCU.cpp.0.o \
 libraries/AP_IOMCU/fw_uploader.cpp.0.o \
 libraries/AP_Parachute/AP_Parachute.cpp.0.o \
 libraries/AP_RAMTRON/AP_RAMTRON.cpp.0.o \
 libraries/AP_RCProtocol/AP_RCProtocol.cpp.0.o \
 libraries/AP_RCProtocol/AP_RCProtocol_DSM.cpp.0.o \
 libraries/AP_RCProtocol/AP_RCProtocol_IBUS.cpp.0.o \
 libraries/AP_RCProtocol/AP_RCProtocol_PPMSum.cpp.0.o \
 libraries/AP_RCProtocol/AP_RCProtocol_SBUS.cpp.0.o \
 libraries/AP_RCProtocol/AP_RCProtocol_SRXL.cpp.0.o \
 libraries/AP_RCProtocol/AP_RCProtocol_ST24.cpp.0.o \
 libraries/AP_RCProtocol/AP_RCProtocol_SUMD.cpp.0.o \
 libraries/AP_RCProtocol/SoftSerial.cpp.0.o \
 libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp.4.o \
 libraries/AP_RCProtocol/AP_RCProtocol_FPort.cpp.4.o \
 libraries/AP_Radio/AP_Radio.cpp.0.o \
 libraries/AP_Radio/AP_Radio_backend.cpp.0.o \
 libraries/AP_Radio/AP_Radio_bk2425.cpp.0.o \
 libraries/AP_Radio/AP_Radio_cc2500.cpp.0.o \
 libraries/AP_Radio/AP_Radio_cypress.cpp.0.o \
 libraries/AP_Radio/driver_bk2425.cpp.0.o \
 libraries/AP_Radio/driver_cc2500.cpp.0.o \
 libraries/AP_TempCalibration/AP_TempCalibration.cpp.0.o \
 libraries/AP_VisualOdom/AP_VisualOdom.cpp.0.o \
 libraries/AP_VisualOdom/AP_VisualOdom_Backend.cpp.0.o \
 libraries/AP_VisualOdom/AP_VisualOdom_MAV.cpp.0.o \
 libraries/AP_BLHeli/AP_BLHeli.cpp.4.o \
 libraries/AP_ROMFS/AP_ROMFS.cpp.0.o \
 libraries/AP_ROMFS/tinfgzip.cpp.0.o \
 libraries/AP_ROMFS/tinflate.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_AirSimSITL.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_Backend.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_LightWareSF40C.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_LightWareSF40C_v09.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_MAV.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_MorseSITL.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_RPLidarA2.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_RangeFinder.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_SITL.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_TeraRangerTower.cpp.0.o \
 libraries/AP_Proximity/AP_Proximity_TeraRangerTowerEvo.cpp.0.o \
 libraries/AP_Gripper/AP_Gripper.cpp.0.o \
 libraries/AP_Gripper/AP_Gripper_Backend.cpp.0.o \
 libraries/AP_Gripper/AP_Gripper_EPM.cpp.0.o \
 libraries/AP_Gripper/AP_Gripper_Servo.cpp.0.o \
 libraries/AP_RTC/AP_RTC.cpp.0.o \
 libraries/AP_RTC/JitterCorrection.cpp.0.o \
 libraries/AC_Sprayer/AC_Sprayer.cpp.0.o \
 libraries/AC_Fence/AC_PolyFence_loader.cpp.0.o \
 libraries/AC_Fence/AC_Fence.cpp.4.o \
 libraries/AC_Avoidance/AP_OABendyRuler.cpp.0.o \
 libraries/AC_Avoidance/AP_OADatabase.cpp.0.o \
 libraries/AC_Avoidance/AP_OADijkstra.cpp.0.o \
 libraries/AC_Avoidance/AP_OAPathPlanner.cpp.0.o \
 libraries/AC_Avoidance/AP_OAVisGraph.cpp.0.o \
 libraries/AC_Avoidance/AC_Avoid.cpp.4.o \
 libraries/AP_LandingGear/AP_LandingGear.cpp.0.o \
 libraries/AP_RobotisServo/AP_RobotisServo.cpp.0.o \
 libraries/AP_ToshibaCAN/AP_ToshibaCAN.cpp.0.o \
 libraries/AP_NMEA_Output/AP_NMEA_Output.cpp.0.o \
 libraries/AP_Filesystem/AP_Filesystem.cpp.0.o \
 libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp.0.o \
 libraries/AP_Filesystem/AP_Filesystem_posix.cpp.0.o \
 libraries/AP_Filesystem/posix_compat.cpp.0.o \
 libraries/AP_ADSB/AP_ADSB.cpp.4.o \
 libraries/AC_PID/AC_HELI_PID.cpp.0.o \
 libraries/AC_PID/AC_P.cpp.0.o \
 libraries/AC_PID/AC_PI.cpp.0.o \
 libraries/AC_PID/AC_PID.cpp.0.o \
 libraries/AC_PID/AC_PID_2D.cpp.0.o \
 libraries/AC_PID/AC_PI_2D.cpp.0.o \
 libraries/AP_SerialLED/AP_SerialLED.cpp.0.o \
 libraries/AP_Hott_Telem/AP_Hott_Telem.cpp.0.o \
 libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp.0.o \
 libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp.0.o \
 libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.cpp.0.o \
 libraries/AC_AttitudeControl/AC_PosControl_Sub.cpp.0.o \
 libraries/AC_AttitudeControl/ControlMonitor.cpp.0.o \
 libraries/AC_AttitudeControl/AC_AttitudeControl.cpp.4.o \
 libraries/AC_AttitudeControl/AC_PosControl.cpp.4.o \
 libraries/AC_InputManager/AC_InputManager.cpp.0.o \
 libraries/AC_InputManager/AC_InputManager_Heli.cpp.0.o \
 libraries/AC_PrecLand/AC_PrecLand.cpp.0.o \
 libraries/AC_PrecLand/AC_PrecLand_Companion.cpp.0.o \
 libraries/AC_PrecLand/AC_PrecLand_IRLock.cpp.0.o \
 libraries/AC_PrecLand/AC_PrecLand_SITL.cpp.0.o \
 libraries/AC_PrecLand/AC_PrecLand_SITL_Gazebo.cpp.0.o \
 libraries/AC_PrecLand/PosVelEKF.cpp.0.o \
 libraries/AC_Autorotation/AC_Autorotation.cpp.0.o \
 libraries/AC_WPNav/AC_Circle.cpp.0.o \
 libraries/AC_WPNav/AC_Loiter.cpp.0.o \
 libraries/AC_WPNav/AC_WPNav.cpp.0.o \
 libraries/AC_WPNav/AC_WPNav_OA.cpp.0.o \
 libraries/AP_Camera/AP_Camera.cpp.0.o \
 libraries/AP_Camera/AP_Camera_SoloGimbal.cpp.0.o \
 libraries/AP_IRLock/AP_IRLock_I2C.cpp.0.o \
 libraries/AP_IRLock/AP_IRLock_SITL.cpp.0.o \
 libraries/AP_IRLock/AP_IRLock_SITL_Gazebo.cpp.0.o \
 libraries/AP_IRLock/IRLock.cpp.0.o \
 libraries/AP_InertialNav/AP_InertialNav_NavEKF.cpp.0.o \
 libraries/AP_Motors/AP_Motors6DOF.cpp.0.o \
 libraries/AP_Motors/AP_MotorsCoax.cpp.0.o \
 libraries/AP_Motors/AP_MotorsHeli.cpp.0.o \
 libraries/AP_Motors/AP_MotorsHeli_Dual.cpp.0.o \
 libraries/AP_Motors/AP_MotorsHeli_Quad.cpp.0.o \
 libraries/AP_Motors/AP_MotorsHeli_RSC.cpp.0.o \
 libraries/AP_Motors/AP_MotorsHeli_Single.cpp.0.o \
 libraries/AP_Motors/AP_MotorsHeli_Swash.cpp.0.o \
 libraries/AP_Motors/AP_MotorsMatrix.cpp.0.o \
 libraries/AP_Motors/AP_MotorsMatrixTS.cpp.0.o \
 libraries/AP_Motors/AP_MotorsMulticopter.cpp.0.o \
 libraries/AP_Motors/AP_MotorsSingle.cpp.0.o \
 libraries/AP_Motors/AP_MotorsTailsitter.cpp.0.o \
 libraries/AP_Motors/AP_MotorsTri.cpp.0.o \
 libraries/AP_Motors/AP_Motors_Class.cpp.0.o \
 libraries/AP_RCMapper/AP_RCMapper.cpp.0.o \
 libraries/AP_Avoidance/AP_Avoidance.cpp.4.o \
 libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp.0.o \
 libraries/AP_SmartRTL/AP_SmartRTL.cpp.0.o \
 libraries/AP_Stats/AP_Stats.cpp.0.o \
 libraries/AP_Beacon/AP_Beacon.cpp.0.o \
 libraries/AP_Beacon/AP_Beacon_Backend.cpp.0.o \
 libraries/AP_Beacon/AP_Beacon_Marvelmind.cpp.0.o \
 libraries/AP_Beacon/AP_Beacon_Pozyx.cpp.0.o \
 libraries/AP_Beacon/AP_Beacon_SITL.cpp.0.o \
 libraries/AP_Arming/AP_Arming.cpp.4.o \
 libraries/AP_WheelEncoder/AP_WheelEncoder.cpp.0.o \
 libraries/AP_WheelEncoder/AP_WheelRateControl.cpp.0.o \
 libraries/AP_WheelEncoder/WheelEncoder_Backend.cpp.0.o \
 libraries/AP_WheelEncoder/WheelEncoder_Quadrature.cpp.0.o \
 libraries/AP_WheelEncoder/WheelEncoder_SITL_Quadrature.cpp.0.o \
 libraries/AP_Winch/AP_Winch.cpp.0.o \
 libraries/AP_Winch/AP_Winch_Servo.cpp.0.o \
 libraries/AP_Follow/AP_Follow.cpp.4.o \
 libraries/AP_Devo_Telem/AP_Devo_Telem.cpp.0.o \
 libraries/AP_OSD/AP_OSD.cpp.0.o \
 libraries/AP_OSD/AP_OSD_Backend.cpp.0.o \
 libraries/AP_OSD/AP_OSD_MAX7456.cpp.0.o \
 libraries/AP_OSD/AP_OSD_SITL.cpp.0.o \
 libraries/AP_OSD/AP_OSD_Screen.cpp.0.o \
 libraries/AP_OSD/AP_OSD_Setting.cpp.0.o \
 libraries/AC_AutoTune/AC_AutoTune.cpp.0.o \
 libraries/AP_KDECAN/AP_KDECAN.cpp.0.o \
 libraries/AP_HAL_SITL/AnalogIn.cpp.0.o \
 libraries/AP_HAL_SITL/GPIO.cpp.0.o \
 libraries/AP_HAL_SITL/HAL_SITL_Class.cpp.0.o \
 libraries/AP_HAL_SITL/RCInput.cpp.0.o \
 libraries/AP_HAL_SITL/RCOutput.cpp.0.o \
 libraries/AP_HAL_SITL/SITL_State.cpp.0.o \
 libraries/AP_HAL_SITL/Scheduler.cpp.0.o \
 libraries/AP_HAL_SITL/Semaphores.cpp.0.o \
 libraries/AP_HAL_SITL/Storage.cpp.0.o \
 libraries/AP_HAL_SITL/ToneAlarm_SF.cpp.0.o \
 libraries/AP_HAL_SITL/UARTDriver.cpp.0.o \
 libraries/AP_HAL_SITL/UART_utils.cpp.0.o \
 libraries/AP_HAL_SITL/Util.cpp.0.o \
 libraries/AP_HAL_SITL/sitl_airspeed.cpp.0.o \
 libraries/AP_HAL_SITL/sitl_gps.cpp.0.o \
 libraries/AP_HAL_SITL/sitl_rangefinder.cpp.0.o \
 libraries/AP_HAL_SITL/system.cpp.0.o \
 libraries/AP_HAL_SITL/SITL_cmdline.cpp.4.o \
 libraries/SITL/SIM_ADSB.cpp.0.o \
 libraries/SITL/SIM_AirSim.cpp.0.o \
 libraries/SITL/SIM_Aircraft.cpp.0.o \
 libraries/SITL/SIM_BalanceBot.cpp.0.o \
 libraries/SITL/SIM_Balloon.cpp.0.o \
 libraries/SITL/SIM_Buzzer.cpp.0.o \
 libraries/SITL/SIM_CRRCSim.cpp.0.o \
 libraries/SITL/SIM_Calibration.cpp.0.o \
 libraries/SITL/SIM_FlightAxis.cpp.0.o \
 libraries/SITL/SIM_Frame.cpp.0.o \
 libraries/SITL/SIM_Gazebo.cpp.0.o \
 libraries/SITL/SIM_Gimbal.cpp.0.o \
 libraries/SITL/SIM_Gripper_EPM.cpp.0.o \
 libraries/SITL/SIM_Gripper_Servo.cpp.0.o \
 libraries/SITL/SIM_Helicopter.cpp.0.o \
 libraries/SITL/SIM_ICEngine.cpp.0.o \
 libraries/SITL/SIM_JSBSim.cpp.0.o \
 libraries/SITL/SIM_Morse.cpp.0.o \
 libraries/SITL/SIM_Motor.cpp.0.o \
 libraries/SITL/SIM_Multicopter.cpp.0.o \
 libraries/SITL/SIM_Parachute.cpp.0.o \
 libraries/SITL/SIM_Plane.cpp.0.o \
 libraries/SITL/SIM_Precland.cpp.0.o \
 libraries/SITL/SIM_QuadPlane.cpp.0.o \
 libraries/SITL/SIM_Rover.cpp.0.o \
 libraries/SITL/SIM_Sailboat.cpp.0.o \
 libraries/SITL/SIM_Scrimmage.cpp.0.o \
 libraries/SITL/SIM_SilentWings.cpp.0.o \
 libraries/SITL/SIM_SingleCopter.cpp.0.o \
 libraries/SITL/SIM_Sprayer.cpp.0.o \
 libraries/SITL/SIM_Submarine.cpp.0.o \
 libraries/SITL/SIM_ToneAlarm.cpp.0.o \
 libraries/SITL/SIM_Tracker.cpp.0.o \
 libraries/SITL/SIM_Vicon.cpp.0.o \
 libraries/SITL/SIM_Webots.cpp.0.o \
 libraries/SITL/SIM_XPlane.cpp.0.o \
 libraries/SITL/SIM_last_letter.cpp.0.o \
 libraries/SITL/SITL.cpp.0.o \
 libraries/AP_Scripting/AP_Scripting.cpp.0.o \
 libraries/AP_Scripting/lua_bindings.cpp.0.o \
 libraries/AP_Scripting/lua_boxed_numerics.cpp.0.o \
 libraries/AP_Scripting/lua_generated_bindings.cpp.0.o \
 libraries/AP_Scripting/lua_scripts.cpp.0.o \
-o one_bitcode.bc



 libraries/AP_Scripting/lua/src/lapi.c.0.o \
 libraries/AP_Scripting/lua/src/lauxlib.c.0.o \
 libraries/AP_Scripting/lua/src/lbaselib.c.0.o \
 libraries/AP_Scripting/lua/src/lbitlib.c.0.o \
 libraries/AP_Scripting/lua/src/lcode.c.0.o \
 libraries/AP_Scripting/lua/src/lcorolib.c.0.o \
 libraries/AP_Scripting/lua/src/lctype.c.0.o \
 libraries/AP_Scripting/lua/src/ldblib.c.0.o \
 libraries/AP_Scripting/lua/src/ldebug.c.0.o \
 libraries/AP_Scripting/lua/src/ldo.c.0.o \
 libraries/AP_Scripting/lua/src/ldump.c.0.o \
 libraries/AP_Scripting/lua/src/lfunc.c.0.o \
 libraries/AP_Scripting/lua/src/lgc.c.0.o \
 libraries/AP_Scripting/lua/src/linit.c.0.o \
 libraries/AP_Scripting/lua/src/liolib.c.0.o \
 libraries/AP_Scripting/lua/src/llex.c.0.o \
 libraries/AP_Scripting/lua/src/lmathlib.c.0.o \
 libraries/AP_Scripting/lua/src/lmem.c.0.o \
 libraries/AP_Scripting/lua/src/loadlib.c.0.o \
 libraries/AP_Scripting/lua/src/lobject.c.0.o \
 libraries/AP_Scripting/lua/src/lopcodes.c.0.o \
 libraries/AP_Scripting/lua/src/loslib.c.0.o \
 libraries/AP_Scripting/lua/src/lparser.c.0.o \
 libraries/AP_Scripting/lua/src/lstate.c.0.o \
 libraries/AP_Scripting/lua/src/lstring.c.0.o \
 libraries/AP_Scripting/lua/src/lstrlib.c.0.o \
 libraries/AP_Scripting/lua/src/ltable.c.0.o \
 libraries/AP_Scripting/lua/src/ltablib.c.0.o \
 libraries/AP_Scripting/lua/src/ltm.c.0.o \
 libraries/AP_Scripting/lua/src/lua.c.0.o \
 libraries/AP_Scripting/lua/src/luac.c.0.o \
 libraries/AP_Scripting/lua/src/lundump.c.0.o \
 libraries/AP_Scripting/lua/src/lutf8lib.c.0.o \
 libraries/AP_Scripting/lua/src/lvm.c.0.o \
 libraries/AP_Scripting/lua/src/lzio.c.0.o
