cd build/sitl

clang++ -Wl,--gc-sections -pthread -flto \
../../build/sitl/after_cmpt.bc \
ArduCopter/AP_Arming.cpp.30.o \
ArduCopter/AP_Rally.cpp.30.o \
ArduCopter/AP_State.cpp.30.o \
ArduCopter/Attitude.cpp.30.o \
ArduCopter/Copter.cpp.30.o \
ArduCopter/GCS_Copter.cpp.30.o \
ArduCopter/GCS_Mavlink.cpp.30.o \
ArduCopter/Log.cpp.30.o \
ArduCopter/Parameters.cpp.30.o \
ArduCopter/RC_Channel.cpp.30.o \
ArduCopter/UserCode.cpp.30.o \
ArduCopter/UserParameters.cpp.30.o \
ArduCopter/afs_copter.cpp.30.o \
ArduCopter/autoyaw.cpp.30.o \
ArduCopter/avoidance_adsb.cpp.30.o \
ArduCopter/baro_ground_effect.cpp.30.o \
ArduCopter/commands.cpp.30.o \
ArduCopter/compassmot.cpp.30.o \
ArduCopter/crash_check.cpp.30.o \
ArduCopter/ekf_check.cpp.30.o \
ArduCopter/esc_calibration.cpp.30.o \
ArduCopter/events.cpp.30.o \
ArduCopter/failsafe.cpp.30.o \
ArduCopter/fence.cpp.30.o \
ArduCopter/heli.cpp.30.o \
ArduCopter/inertia.cpp.30.o \
ArduCopter/land_detector.cpp.30.o \
ArduCopter/landing_gear.cpp.30.o \
ArduCopter/leds.cpp.30.o \
ArduCopter/mode.cpp.30.o \
ArduCopter/mode_acro.cpp.30.o \
ArduCopter/mode_acro_heli.cpp.30.o \
ArduCopter/mode_althold.cpp.30.o \
ArduCopter/mode_auto.cpp.30.o \
ArduCopter/mode_autorotate.cpp.30.o \
ArduCopter/mode_autotune.cpp.30.o \
ArduCopter/mode_avoid_adsb.cpp.30.o \
ArduCopter/mode_brake.cpp.30.o \
ArduCopter/mode_circle.cpp.30.o \
ArduCopter/mode_drift.cpp.30.o \
ArduCopter/mode_flip.cpp.30.o \
ArduCopter/mode_flowhold.cpp.30.o \
ArduCopter/mode_follow.cpp.30.o \
ArduCopter/mode_guided.cpp.30.o \
ArduCopter/mode_guided_nogps.cpp.30.o \
ArduCopter/mode_land.cpp.30.o \
ArduCopter/mode_loiter.cpp.30.o \
ArduCopter/mode_poshold.cpp.30.o \
ArduCopter/mode_rtl.cpp.30.o \
ArduCopter/mode_smart_rtl.cpp.30.o \
ArduCopter/mode_sport.cpp.30.o \
ArduCopter/mode_stabilize.cpp.30.o \
ArduCopter/mode_stabilize_heli.cpp.30.o \
ArduCopter/mode_systemid.cpp.30.o \
ArduCopter/mode_throw.cpp.30.o \
ArduCopter/mode_zigzag.cpp.30.o \
ArduCopter/motor_test.cpp.30.o \
ArduCopter/motors.cpp.30.o \
ArduCopter/navigation.cpp.30.o \
ArduCopter/precision_landing.cpp.30.o \
ArduCopter/radio.cpp.30.o \
ArduCopter/sensors.cpp.30.o \
ArduCopter/setup.cpp.30.o \
ArduCopter/standby.cpp.30.o \
ArduCopter/surface_tracking.cpp.30.o \
ArduCopter/system.cpp.30.o \
ArduCopter/takeoff.cpp.30.o \
ArduCopter/terrain.cpp.30.o \
ArduCopter/toy_mode.cpp.30.o \
ArduCopter/tuning.cpp.30.o \
ArduCopter/version.cpp.30.o \
-obin/arducopter \
-Wl,-Bstatic -Llib -lArduCopter_libs \
-Wl,-Bdynamic -lm


echo "[Succeeded] the executable file can be found in :"
realpath bin/arducopter